FROM  node

WORKDIR /app

COPY package*.json ./ 

RUN npm install

COPY . .

EXPOSE 3001

CMD [ "node", "app.js" ]

# et dans le terminal
# docker build --no-cache -t nodeapp .
# docker run --name containernode -p 5000:3001 -it nodeapp
